### ISSUE TITLE
Scripts not executed

### ISSUE THREAD

**Issue by adamschwartz** [cloudflare-apps/add-html#1]
I think we need to support something like this. Thoughts?

Possible implementations:
http://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml

**Comment by zackbloom** [comment]
Yea, I can absolutely add this.

**Comment by adamschwartz** [comment]
Sweet! Thx

**Comment by zackbloom** [comment]
Closed by https://github.com/EagerApps/AddHTML/commit/2e81bd8e613bcf40abe7060ee43f536a67d8c0f5

**Comment by zackbloom** [comment]
Note that non-https external scripts will not work in the preview at the moment, as the preview is an https page.
